# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedAlertMap < Formula
  desc "Real-time Israeli Pikud HaOref alert map with zone polygons"
  homepage "https://github.com/aviv4339/red-alert-map"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aviv4339/red-alert-map/releases/download/v1.0.0/red-alert-map_darwin_amd64.tar.gz"
      sha256 "69fe2a5182d8dfb0e3997dad511a98038066acaf19d16ad036a42265e7fa7b85"

      define_method(:install) do
        bin.install "red-alert-map"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aviv4339/red-alert-map/releases/download/v1.0.0/red-alert-map_darwin_arm64.tar.gz"
      sha256 "c791d554cea264e063f54a7904e46eb08324381b7b3af278956a2bf0d200999a"

      define_method(:install) do
        bin.install "red-alert-map"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviv4339/red-alert-map/releases/download/v1.0.0/red-alert-map_linux_amd64.tar.gz"
      sha256 "7e8dc23d56923425ba2d833f9314d224d3d3bc8d57f21e69731fe7ac478dfc92"
      define_method(:install) do
        bin.install "red-alert-map"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aviv4339/red-alert-map/releases/download/v1.0.0/red-alert-map_linux_arm64.tar.gz"
      sha256 "1a8171934048f9d02f48308ee063b28435b499ea44b2d1999c636be85681e954"
      define_method(:install) do
        bin.install "red-alert-map"
      end
    end
  end

  test do
    assert_match "Red Alert Map", shell_output("#{bin}/red-alert-map --version")
  end
end
