# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cornholio < Formula
  desc "AI Agent Reporter & Analyzer - The Great Cornholio sees all"
  homepage "https://github.com/aviv4339/cornholio"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aviv4339/cornholio/releases/download/v0.1.0/cornholio_0.1.0_darwin_amd64.tar.gz"
    sha256 "5b75b133bcfa39741fcfccefa30e0536e4ced882aaa17764f812b65fbc116a9a"

    def install
      bin.install "cornholio"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aviv4339/cornholio/releases/download/v0.1.0/cornholio_0.1.0_darwin_arm64.tar.gz"
    sha256 "3dd8e908b33545a39712672ffffce982e3b7839a90b274589e819910027e6d8c"

    def install
      bin.install "cornholio"
    end
  end

  test do
    system "#{bin}/cornholio", "version"
  end
end
