# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cornholio < Formula
  desc "AI Agent Reporter & Analyzer - The Great Cornholio sees all"
  homepage "https://github.com/aviv4339/cornholio"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/aviv4339/cornholio/releases/download/v0.2.0/cornholio_0.2.0_darwin_amd64.tar.gz"
    sha256 "1137f22fcc08b66423c11bd74d5c4f7ce27ed7d28ea2e8a628a684cee51e7146"

    def install
      bin.install "cornholio"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/aviv4339/cornholio/releases/download/v0.2.0/cornholio_0.2.0_darwin_arm64.tar.gz"
    sha256 "d3acd8756849be6776f109fa25ee7d3f59ea2fe6ed58c6e576a987edb7b28840"

    def install
      bin.install "cornholio"
    end
  end

  test do
    system "#{bin}/cornholio", "version"
  end
end
